---
- name: Apply all available package updates
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  environment:
    DEBIAN_FRONTEND: noninteractive
    NEEDRESTART_MODE: a

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive
    NEEDRESTART_MODE: a

- name: Enable periodic unattended security upgrades
  ansible.builtin.copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Remove packages that are no longer required
  ansible.builtin.apt:
    autoremove: true
  environment:
    DEBIAN_FRONTEND: noninteractive
    NEEDRESTART_MODE: a
