---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: Load audit rules
  ansible.builtin.command: augenrules --load
  changed_when: true
